version: 2.1

orbs:
    aws-ecr: circleci/aws-ecr@6.1.0
    aws-ecs: circleci/aws-ecs@0.0.8

jobs:
    test:
        docker:
            - image: circleci/note:14
        steps:
            - checkout
            - run:
                name: install dependencies
                command: npm install
            - run:
                name: unit test
                command: npm run test

workflows:
    build_and_push_image:
        jobs:
        - test
        - aws-ecr/build-and-push-image:
            requires:
                - test
            region: AWS_REGION
            account-url: AWS_ECR_ACCOUNT_URL
            repo: 'book-butterfly-api'
            tag: "${CIRCLE_SHA1}"
        - aws-ecs/deploy-service-update:
            requires:
                - aws-ecr/build-and-push-image
            family: 'book-butterfly-api'
            cluster-name: 'book-butterfly'
            service-name: 'book-butterfly-api2'
            container-image-name-updates: 'container=book-butterfly-api,tag=${CIRCLE_SHA1}'
